FROM node:20-alpine
WORKDIR /app
COPY package.json ./
RUN npm install -g pnpm@10.33.0
COPY pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm run build
EXPOSE 4000
CMD ["node", "dist/main.js"]